"""Shared Flux emission helpers.

Detectors emit only their detection stage; the header, the severity mapping and
the write epilogue are identical across detectors and live here.  Keeping them
in one place is what makes the generated scripts golden-file testable.
"""

from __future__ import annotations

from collections.abc import Sequence

__all__ = [
    "FLUX_DOC_LINK",
    "escape_flux_string",
    "flux_float",
    "flux_header",
    "severity_expr",
    "write_stage",
]

#: The single explanatory link allowed in generated output.
FLUX_DOC_LINK = (
    "https://taskautomation.org/automated-task-scheduling-orchestration/"
    "anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/"
)


def escape_flux_string(value: str) -> str:
    """Escape a Python string for interpolation into a Flux string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def flux_float(value: float) -> str:
    """Render a Python float as a Flux float literal (always with a decimal point)."""
    if value == float("inf"):
        return 'float(v: "+Inf")'
    if value == float("-inf"):
        return 'float(v: "-Inf")'
    text = repr(float(value))
    if "e" in text or "E" in text or "." in text or "Inf" in text:
        return text
    return text + ".0"


def flux_header(task_name: str, detector: str, notes: Sequence[str] = ()) -> str:
    """Build the comment block that tops every generated script."""
    lines = [
        f"// Anomaly task: {task_name}",
        f"// Detector:     {detector}",
        "// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.",
    ]
    lines.extend(f"// {note}" for note in notes)
    lines.append(f"// Background on Flux threshold alerting: {FLUX_DOC_LINK}")
    return "\n".join(lines)


def severity_expr(score: str, threshold: str) -> str:
    """Flux expression mapping a score/threshold ratio onto a severity string.

    Mirrors :meth:`tsdb_anomaly_task.models.Severity.from_ratio` exactly so a
    server-side task and a client-side runner label the same point identically.
    """
    ratio = f"(math.abs(x: {score}) / math.abs(x: {threshold}))"
    return f'if {ratio} >= 2.0 then "critical" else if {ratio} >= 1.25 then "warning" else "info"'


def write_stage(
    *,
    flag_measurement: str,
    detector: str,
    bucket: str,
    org: str | None = None,
    group_by: Sequence[str] = (),
    extra_tags: dict[str, str] | None = None,
    indent: str = "  ",
) -> str:
    """Emit the shared ``map`` + ``group`` + ``to`` epilogue.

    The detection stage is expected to have produced ``_score``, ``_threshold``
    and ``_reason`` columns alongside ``_time`` and ``_value``.  This stage
    reshapes them into the flag record, derives severity, promotes the tag
    columns into the group key so ``to()`` writes them as tags, and writes.
    """
    tag_cols = [*list(group_by), "detector", "severity"]
    tag_assignments = "".join(
        f'\n{indent}    {key}: "{escape_flux_string(value)}",'
        for key, value in sorted((extra_tags or {}).items())
    )
    if extra_tags:
        tag_cols.extend(sorted(extra_tags))

    all_cols = [*tag_cols, "_measurement", "_field"]
    cols = ", ".join(f'"{escape_flux_string(c)}"' for c in all_cols)
    org_arg = f', org: "{escape_flux_string(org)}"' if org else ""

    return "\n".join(
        [
            f"{indent}|> map(fn: (r) => ({{ r with",
            f'{indent}    _measurement: "{escape_flux_string(flag_measurement)}",',
            f'{indent}    _field: "value",',
            f'{indent}    detector: "{escape_flux_string(detector)}",',
            f"{indent}    severity: {severity_expr('r._score', 'r._threshold')}," + tag_assignments,
            f"{indent}}}))",
            f"{indent}|> group(columns: [{cols}])",
            f'{indent}|> to(bucket: "{escape_flux_string(bucket)}"{org_arg},',
            f"{indent}      fieldFn: (r) => ({{",
            f'{indent}          "value": r._value,',
            f'{indent}          "score": r._score,',
            f'{indent}          "threshold": r._threshold,',
            f'{indent}          "reason": r._reason,',
            f"{indent}      }}))",
        ]
    )
