// Anomaly task: sensor-deadman
// Detector:     deadman(tolerance=15m)
// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.
// A server-side deadman only sees series that returned at least one row in the task window. A sensor silent for longer than the window disappears entirely and must be caught by comparing against an expected-series list.
// Background on Flux threshold alerting: https://taskautomation.org/automated-task-scheduling-orchestration/anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/

import "math"

option task = {name: "sensor-deadman", every: 5m, offset: 30s}

from(bucket: "telemetry")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "sensor")
  |> filter(fn: (r) => r._field == "temperature")
  |> filter(fn: (r) => exists r.host)
  |> group(columns: ["host"])
  |> sort(columns: ["_time"])
  |> last()
  |> map(fn: (r) => ({ r with
      _score: float(v: int(v: now()) - int(v: r._time)) / 1000000000.0,
      _threshold: 900.0,
      _reason: "series stopped reporting for longer than 15m",
  }))
  |> filter(fn: (r) => r._score > 900.0)
  |> map(fn: (r) => ({ r with
      _measurement: "anomaly",
      _field: "value",
      detector: "deadman",
      severity: if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 2.0 then "critical" else if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 1.25 then "warning" else "info",
  }))
  |> group(columns: ["host", "detector", "severity", "_measurement", "_field"])
  |> to(bucket: "anomalies",
        fieldFn: (r) => ({
            "value": r._value,
            "score": r._score,
            "threshold": r._threshold,
            "reason": r._reason,
        }))
