// Anomaly task: cpu-mad
// Detector:     mad(k=3.5, window=all)
// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.
// MAD is evaluated over the whole task window, not a rolling window.
// Consistency constant 1.4826 = 1/inverse-normal-CDF(0.75).
// Background on Flux threshold alerting: https://taskautomation.org/automated-task-scheduling-orchestration/anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/

import "math"

option task = {name: "cpu-mad", every: 5m, offset: 30s}

// Whole-window MAD: the median and MAD are computed once over the
// task's range and applied to every row (unlike the client-side
// runner, which excludes each point from its own baseline).
data = from(bucket: "telemetry")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage")
  |> group()
  |> sort(columns: ["_time"])

_median = (data
  |> quantile(q: 0.5, method: "exact_selector")
  |> findRecord(fn: (key) => true, idx: 0))._value

_scaledMad = (data
  |> map(fn: (r) => ({ r with _value: math.abs(x: r._value - _median) }))
  |> quantile(q: 0.5, method: "exact_selector")
  |> findRecord(fn: (key) => true, idx: 0))._value * 1.4826022185056018

data
  |> filter(fn: (r) => _scaledMad > 0.0)
  |> map(fn: (r) => ({ r with
      _score: (r._value - _median) / _scaledMad,
      _threshold: 3.5,
      _reason: "robust z-score exceeds k=3.5 scaled MADs",
  }))
  |> filter(fn: (r) => math.abs(x: r._score) >= 3.5)
  |> map(fn: (r) => ({ r with
      _measurement: "anomaly",
      _field: "value",
      detector: "mad",
      severity: if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 2.0 then "critical" else if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 1.25 then "warning" else "info",
  }))
  |> group(columns: ["detector", "severity", "_measurement", "_field"])
  |> to(bucket: "anomalies",
        fieldFn: (r) => ({
            "value": r._value,
            "score": r._score,
            "threshold": r._threshold,
            "reason": r._reason,
        }))
