// Anomaly task: sensor-rate
// Detector:     rate_of_change(max=2/1m)
// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.
// derivative() reports the rate at the later of each sample pair, matching the client-side runner.
// Background on Flux threshold alerting: https://taskautomation.org/automated-task-scheduling-orchestration/anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/

import "math"

option task = {name: "sensor-rate", every: 5m, offset: 30s}

originals = from(bucket: "telemetry")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "sensor")
  |> filter(fn: (r) => r._field == "temperature")
  |> filter(fn: (r) => exists r.host)
  |> group(columns: ["host"])
  |> sort(columns: ["_time"])

originals
  |> derivative(unit: 1m, nonNegative: false, columns: ["_value"], timeColumn: "_time")
  |> rename(columns: {_value: "_score"})
  |> filter(fn: (r) => r._score > 2.0 or r._score < -0.5)
  |> map(fn: (r) => ({ r with
      _value: r._score,
      _threshold: if r._score > 0.0 then 2.0 else -0.5,
      _reason: "rate of change exceeds the configured bound per 1m",
  }))
  |> map(fn: (r) => ({ r with
      _measurement: "anomaly",
      _field: "value",
      detector: "rate_of_change",
      severity: if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 2.0 then "critical" else if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 1.25 then "warning" else "info",
  }))
  |> group(columns: ["host", "detector", "severity", "_measurement", "_field"])
  |> to(bucket: "anomalies",
        fieldFn: (r) => ({
            "value": r._value,
            "score": r._score,
            "threshold": r._threshold,
            "reason": r._reason,
        }))
