// Anomaly task: temperature-watch
// Detector:     threshold(>= 14 and <= 26)
// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.
// stateCount emits a run only once it reaches consecutive_points=2; the Python runner back-fills the earlier samples of the same run.
// Background on Flux threshold alerting: https://taskautomation.org/automated-task-scheduling-orchestration/anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/

import "math"

option task = {name: "temperature-watch", every: 5m, offset: 30s}

from(bucket: "telemetry")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "sensor")
  |> filter(fn: (r) => r._field == "temperature")
  |> filter(fn: (r) => exists r.host)
  |> group(columns: ["host"])
  |> sort(columns: ["_time"])
  |> stateCount(fn: (r) => r._value > 26.0 or r._value < 14.0, column: "_breachRun")
  |> filter(fn: (r) => r._breachRun >= 2)
  |> map(fn: (r) => ({ r with
      _score: r._value,
      _threshold: if r._value > 26.0 then 26.0 else 14.0,
      _reason: if r._value > 26.0 then "value above upper limit 26" else "value below lower limit 14",
  }))
  |> map(fn: (r) => ({ r with
      _measurement: "anomaly",
      _field: "value",
      detector: "threshold",
      severity: if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 2.0 then "critical" else if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 1.25 then "warning" else "info",
  }))
  |> group(columns: ["host", "detector", "severity", "_measurement", "_field"])
  |> to(bucket: "anomalies",
        fieldFn: (r) => ({
            "value": r._value,
            "score": r._score,
            "threshold": r._threshold,
            "reason": r._reason,
        }))
