// Anomaly task: cpu-hot
// Detector:     threshold(<= 90)
// Generated by tsdb-anomaly-task. Edit the Python definition, not this file.
// Hourly CPU ceiling check.
// Background on Flux threshold alerting: https://taskautomation.org/automated-task-scheduling-orchestration/anomaly-detection-and-alerting/threshold-based-alerting-with-flux-and-python-hooks/

import "math"

option task = {name: "cpu-hot", cron: "0 * * * *"}

from(bucket: "telemetry")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage")
  |> group()
  |> sort(columns: ["_time"])
  |> filter(fn: (r) => r._value > 90.0)
  |> map(fn: (r) => ({ r with
      _score: r._value,
      _threshold: 90.0,
      _reason: "value above upper limit 90",
  }))
  |> map(fn: (r) => ({ r with
      _measurement: "anomaly",
      _field: "value",
      detector: "threshold",
      severity: if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 2.0 then "critical" else if (math.abs(x: r._score) / math.abs(x: r._threshold)) >= 1.25 then "warning" else "info",
      env: "prod",
  }))
  |> group(columns: ["detector", "severity", "env", "_measurement", "_field"])
  |> to(bucket: "anomalies", org: "acme",
        fieldFn: (r) => ({
            "value": r._value,
            "score": r._score,
            "threshold": r._threshold,
            "reason": r._reason,
        }))
